In [1]:
import numpy as np
import pandas as pd
from pandas import read_csv
import statsmodels 
from sklearn.model_selection import train_test_split
import seaborn as sns
from datetime import datetime,date
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
import keras
import math
from sklearn.metrics import mean_absolute_error, mean_squared_error
!pip install --upgrade pip
!pip install -I Cython==0.28.5
!pip install pyarrow

import pandas as pd
import pyarrow
import pyarrow.parquet

  ERROR: Command errored out with exit status 1:
   command: 'c:\users\36203\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\36203\\AppData\\Local\\Temp\\pip-install-oh0_y9iu\\cython_ddf1f29aae5243219f41fb65a111555f\\setup.py'"'"'; __file__='"'"'C:\\Users\\36203\\AppData\\Local\\Temp\\pip-install-oh0_y9iu\\cython_ddf1f29aae5243219f41fb65a111555f\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\36203\AppData\Local\Temp\pip-wheel-welzzzup'
       cwd: C:\Users\36203\AppData\Local\Temp\pip-install-oh0_y9iu\cython_ddf1f29aae5243219f41fb65a111555f\
  Complete output (316 lines):
  Unable to find pgen, not compiling formal grammar.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  copying cython.py -> build\lib.win-amd64-3.8
  creating bu


  Running setup.py clean for Cython
Failed to build Cython
    Running setup.py install for Cython: started
    Running setup.py install for Cython: finished with status 'error'


In [6]:
train_data = pd.read_csv("/Users/36203/user_3/Kaggle/nfl-impact-detection/train_player_tracking.csv", header=0, index_col=3)
nlf_label= pd.read_csv("/Users/36203/user_3/Kaggle/nfl-impact-detection/train_labels.csv", header=0)
test_df = pd.read_csv('/Users/36203/user_3/Kaggle/nfl-impact-detection/test_player_tracking.csv')
train_data
nlf_label
train_data

gameKey  playID player       x      y     s     a  \
time                                                                          
2018-09-14T00:23:45.500Z    57583      82    H97   38.89  28.06  0.00  0.00   
2018-09-14T00:23:45.599Z    57583      82    H97   38.89  28.06  0.00  0.00   
2018-09-14T00:23:45.700Z    57583      82    H97   38.89  28.06  0.00  0.00   
2018-09-14T00:23:45.799Z    57583      82    H97   38.88  28.05  0.00  0.00   
2018-09-14T00:23:45.900Z    57583      82    H97   38.88  28.05  0.00  0.00   
...                           ...     ...    ...     ...    ...   ...   ...   
2019-12-10T04:33:24.099Z    58107    4362    V53  105.15  36.08  0.38  0.35   
2019-12-10T04:33:24.200Z    58107    4362    V53  105.13  36.09  0.29  0.85   
2019-12-10T04:33:24.299Z    58107    4362    V53  105.11  36.10  0.23  0.91   
2019-12-10T04:33:24.400Z    58107    4362    V53  105.08  36.11  0.21  0.69   
2019-12-10T04:33:24.500Z    58107    4362    V53  105.07  36.11  0.19  0.54   

                           dis       o     dir event  
time                                                  
2018-09-14T00:23:45.500Z  0.00  261.28  222.79   NaN  
2018-09-14T00:23:45.599Z  0.00  261.28  221.93   NaN  
2018-09-14T00:23:45.700Z  0.00  261.28  221.21   NaN  
2018-09-14T00:23:45.799Z  0.00  261.28  220.07   NaN  
2018-09-14T00:23:45.900Z  0.00  261.28  220.31   NaN  
...                        ...     ...     ...   ...  
2019-12-10T04:33:24.099Z  0.04  279.23  330.97   NaN  
2019-12-10T04:33:24.200Z  0.03  273.65  300.97   NaN  
2019-12-10T04:33:24.299Z  0.02  268.49  279.58   NaN  
2019-12-10T04:33:24.400Z  0.02  266.05  277.68   NaN  
2019-12-10T04:33:24.500Z  0.02  263.55  268.38   NaN  

[333811 rows x 11 columns]

In [7]:
train_data .head()

gameKey  playID player      x      y    s    a  dis  \
time                                                                            
2018-09-14T00:23:45.500Z    57583      82    H97  38.89  28.06  0.0  0.0  0.0   
2018-09-14T00:23:45.599Z    57583      82    H97  38.89  28.06  0.0  0.0  0.0   
2018-09-14T00:23:45.700Z    57583      82    H97  38.89  28.06  0.0  0.0  0.0   
2018-09-14T00:23:45.799Z    57583      82    H97  38.88  28.05  0.0  0.0  0.0   
2018-09-14T00:23:45.900Z    57583      82    H97  38.88  28.05  0.0  0.0  0.0   

                               o     dir event  
time                                            
2018-09-14T00:23:45.500Z  261.28  222.79   NaN  
2018-09-14T00:23:45.599Z  261.28  221.93   NaN  
2018-09-14T00:23:45.700Z  261.28  221.21   NaN  
2018-09-14T00:23:45.799Z  261.28  220.07   NaN  
2018-09-14T00:23:45.900Z  261.28  220.31   NaN

In [8]:
nlf_label.isnull().sum()

gameKey            0
playID             0
view               0
video              0
frame              0
label              0
left               0
width              0
top                0
height             0
impact        981594
impactType    981594
confidence    981594
visibility    981594
dtype: int64

In [9]:
nlf_label=nlf_label[~nlf_label.impact.isnull()].copy()
nlf_label.isnull().sum()

gameKey       0
playID        0
view          0
video         0
frame         0
label         0
left          0
width         0
top           0
height        0
impact        0
impactType    0
confidence    0
visibility    0
dtype: int64

In [10]:
train_data.isnull().sum()

gameKey         0
playID          0
player          0
x               0
y               0
s               0
a               0
dis             0
o               0
dir             0
event      323691
dtype: int64

In [11]:
train_data.event.isnull().sum()

323691

In [12]:
train_data = train_data[~train_data.event.isnull()].copy()
train_data.isnull().sum()

gameKey    0
playID     0
player     0
x          0
y          0
s          0
a          0
dis        0
o          0
dir        0
event      0
dtype: int64

In [13]:
!pip install pandas
df = pd.DataFrame()

In [14]:
nlf_label.shape

(2291, 14)

In [15]:
train_data.shape

(10120, 11)

In [16]:
y = nlf_label.impact.astype(int)
y

746       1
754       1
967       1
969       1
1007      1
         ..
980747    1
981284    1
982576    1
982581    1
983271    1
Name: impact, Length: 2291, dtype: int32

In [17]:
features = y
X = features
X

746       1
754       1
967       1
969       1
1007      1
         ..
980747    1
981284    1
982576    1
982581    1
983271    1
Name: impact, Length: 2291, dtype: int32

In [18]:
import pandas as pd
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor


features = ['x','y' ,'s','a', 'dis','o','dir']
X = train_data[features]
X

x      y     s     a   dis       o     dir
time                                                                     
2018-09-14T00:23:48.599Z   38.84  28.12  0.00  0.00  0.00  263.90  327.31
2018-09-14T00:23:52.799Z   36.17  28.80  1.12  0.93  0.09  265.16  291.22
2018-09-14T00:23:53.299Z   35.82  28.96  0.79  0.58  0.07  264.19  295.57
2018-09-14T00:23:57.700Z   35.54  28.80  0.03  0.03  0.02  139.36  136.87
2018-09-14T00:24:00.200Z   35.56  28.89  0.00  0.00  0.00  247.29   47.40
...                          ...    ...   ...   ...   ...     ...     ...
2019-12-10T04:33:09.200Z  102.67  35.30  0.17  0.40  0.01  196.64  260.40
2019-12-10T04:33:10.799Z  102.45  35.09  0.77  1.91  0.07  220.83  238.36
2019-12-10T04:33:12.099Z   99.89  36.18  2.48  2.17  0.26  207.92  323.93
2019-12-10T04:33:13.400Z   99.20  37.23  0.59  1.11  0.05  152.63  242.55
2019-12-10T04:33:15.500Z  104.13  34.95  3.75  1.67  0.38  149.97  104.60

[10120 rows x 7 columns]

In [20]:
X = train_data[features].iloc[:].values
X

array([[3.8840e+01, 2.8120e+01, 0.0000e+00, ..., 0.0000e+00, 2.6390e+02,
        3.2731e+02],
       [3.6170e+01, 2.8800e+01, 1.1200e+00, ..., 9.0000e-02, 2.6516e+02,
        2.9122e+02],
       [3.5820e+01, 2.8960e+01, 7.9000e-01, ..., 7.0000e-02, 2.6419e+02,
        2.9557e+02],
       ...,
       [9.9890e+01, 3.6180e+01, 2.4800e+00, ..., 2.6000e-01, 2.0792e+02,
        3.2393e+02],
       [9.9200e+01, 3.7230e+01, 5.9000e-01, ..., 5.0000e-02, 1.5263e+02,
        2.4255e+02],
       [1.0413e+02, 3.4950e+01, 3.7500e+00, ..., 3.8000e-01, 1.4997e+02,
        1.0460e+02]])

In [21]:
y = nlf_label.iloc[:]['impact'].values

In [23]:
y

array([1., 1., 1., ..., 1., 1., 1.])

In [24]:
X

array([[3.8840e+01, 2.8120e+01, 0.0000e+00, ..., 0.0000e+00, 2.6390e+02,
        3.2731e+02],
       [3.6170e+01, 2.8800e+01, 1.1200e+00, ..., 9.0000e-02, 2.6516e+02,
        2.9122e+02],
       [3.5820e+01, 2.8960e+01, 7.9000e-01, ..., 7.0000e-02, 2.6419e+02,
        2.9557e+02],
       ...,
       [9.9890e+01, 3.6180e+01, 2.4800e+00, ..., 2.6000e-01, 2.0792e+02,
        3.2393e+02],
       [9.9200e+01, 3.7230e+01, 5.9000e-01, ..., 5.0000e-02, 1.5263e+02,
        2.4255e+02],
       [1.0413e+02, 3.4950e+01, 3.7500e+00, ..., 3.8000e-01, 1.4997e+02,
        1.0460e+02]])

In [35]:
from sklearn import datasets
from sklearn import svm

X, y = datasets.load_iris(return_X_y=True)

X.shape, y.shape

((150, 4), (150,))

In [46]:
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.4,random_state=42)
train_X.shape, train_y.shape

((90, 4), (90,))

In [47]:
test_X.shape, test_y.shape

((60, 4), (60,))

In [48]:
clf = svm.SVC(kernel='linear', C=1).fit(train_X,train_y)
clf.score(test_X, test_y)

1.0

In [49]:
pd.Series(train_y).value_counts()

2    32
1    31
0    27
dtype: int64

In [33]:
"""train_X, val_X, train_y, val_y =  cross_validation.train_test_split(X,y,test_size=0.2,random_state=42)

model = DecisionTreeRegressor(random_state=1)

model_fit = model.fit(train_X, train_y)

val_prediction = model.predict(val_X)
val_mae = mean_absolute_error(val_predictions, val_y)

#print("Validation MAE: {:,.0f} ".format(val_mae))
"""

NameError: name 'cross_validation' is not defined

In [50]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
train_X, val_X, train_y, val_y = train_test_split(X,y,test_size=0.2,random_state=1)

rf_model = RandomForestRegressor(random_state=1)
#fit
rf_model.fit(train_X, train_y)

rf_val_predictions = rf_model.predict(val_X)
rf_val_mae = mean_absolute_error(rf_val_predictions, val_y)
print("Validation MAE {}".format(rf_val_mae))

Validation MAE 0.036000000000000004
